services:
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-js"
    ports:
      - "4222:4222"
      - "8222:8222"

  bot:
    build: .

  util-bot:
    build: .
    command:
      - python
      - -OO
      - -u
      - /tw/util-bit.py